# Generated by Django 2.2.5 on 2020-04-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_main_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='tell',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.TextField(),
        ),
    ]
